### PR TITLE
Add fiber params

### PR DESCRIPTION
**Pull request by briantaylor89**
Adding all the code on the "proper branch"  this includes the EDFA standalone model.

### CODE REVIEW

**Comment by dutc** [comment]
Could you please rebase these into a single commit?
`$ git rebase -i # interactively squash commits`

https://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/
http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by briantaylor89** [comment]
sorry but this did not work

**Comment by dutc** [comment]
What are the `examples/edfa_model/*.txt` files?

**Comment by briantaylor89** [comment]
These are data files used by the code.

Sent from my iPhone

On Dec 5, 2017, at 12:05 PM, James <notifications@github.com<mailto:notifications@github.com>> wrote:


What are the examples/edfa_model/*.txt files?

**Comment by dutc** [comment]
Are they vendor data files or do we have control over their format?

**Comment by briantaylor89** [comment]
They were provided by vendor.  We can change them.  For now, I’d like these files to remain as is because they are easy for people to digest.

This code is intended to be a standalone example of the implementation that will be based on network element.  It’s not intended to exist like this forever.

**Pull request closed without merging**
