### PR TITLE
Add fiber params

### PR DESCRIPTION
**Pull request by briantaylor89**

### CODE REVIEW

**Comment by dutc** [comment]
Thanks for these fixes.

Please make the following changes:
- rebase & squash into a single logical commit
- rename `utilities.py` to `utils.py`
- rename functions from `dbkm_2_lin` to `dbkm_to_linear` or the like
- prefer returning a namedtuple over returning a dictionary (easier unpacking at call-site)


Questions:
- does speed of light need to be a function (do we expect this to change?)
- could we add simple doctests to these utility functions?

**Comment by dutc** [comment]
Also, please submit pull requests against the proper branch to make viewing diffs easier.

**Comment by briantaylor89** [comment]
Define “proper branch”

**Comment by dutc** [comment]
Submit the pull request against the feature branch to which your feature branch is parented. Notice that your pull request includes changes from me. This is because you're asking me to merge my changes in my branch + your changes in your branch back into my master branch.

Instead, submit the pull request so that I pull your changes into my feature branch. This means that you should not see any commits from me in your pull request: only your work. And, ideally, your work should be squashed into a single logical commit.

**Comment by briantaylor89** [comment]
These functions get used in a long line of other things that all get multiplied together.  So not going to rename the functions.  It’s clear from context what they are and there’s a docstring explaining.
I’m leaving the return a dictionary for now.  Generally not a fan of unpacking with * because the reader doesn’t know what argument is being passed.

Regarding speed of light, I did not want a class for utilities (if so, would define c as a property) and I want us to avoid globals wherever possible.  Globals are a really bad idea generally.  I really do not want to see a bunch of random globals all over the place.

Define what you mean by doctests?  Do you mean an if main?  Do we really need a test to convert wavelength to frequency?  Frankly that stuff is mostly clutter.

Regarding utilites renaming:  I personally really hate calling modules by abbreviations and utils especially.  A module name should be descriptive and while utilities is pretty generic utils is even more so.

-Brian

**Comment by dutc** [comment]
Doctests are lightweight testing integrated into documentation: https://docs.python.org/3.6/library/doctest.html

Small utility functions are a good use-case for this. It's another form of documentation. You can combine this with an `if __name__ == '__main__'` block if you'd like.

Raw tuple or namedtuple returns are the preferred way to returned multiple values within a namespace. Return a dictionary when the return value should be a mapping, not merely some namespace. With a namedtuple, we get both convenience & explicitness.

Globals are not a bad idea in Python, because they are actually module-scoped variables (rather than program-scoped variables, as is the case in other languages.) There is no difference between `module.c` and `module.c()` both are module-scoped "globals." Unless we anticipate that the speed of light may change, then it should just be a (module-level) constant. In the case that it could change, there are officially supported mechanisms for adding properties to modules.

I'll assess whether we need `utils.py` at all. Many of these could be folded into the `__init__.py` or may go into a `consts.py`.

**Comment by briantaylor89** [comment]
I don’t think this is needed for such simple functions.  There is also nothing like this in your code anywhere.

Also, utilities.py is needed because these functions will be used everywhere.  It’s best to have a common location for them so they are not sprinkled at random throughout the modules.

Globals are terrible idea.  There is no reason for using them here.  It’s simply lazy.

Named tuple vs dict:  There are scenarios where I would want the result to be mutable.  For example, I want to try with a different fiber type etc...  In that case I have to create another named tuple with the value in it.

-Brian

**Comment by dutc** [comment]
A module-scoped function is no different than a module-scoped constant, given that the value itself can be assumed to be fixed. What we call "globals" in Python are module-scoped variables. They do not have the traditional downsides of "global" variables in languages that do not have modules.

In this case, there is no difference between a "global" function and a "global" constant, other than that the former requires `()` and has some execution and cognitive penalty. There is insufficient justification at this time to accept these penalties.

If the return value needs to be a mutable object with a single, coherent logical meaning, then you can create a class. Alternatively, if the call-stack is non-linear or the return value's lifetime is not scoped to its immediate call-stack, then a custom object is also a good idea. In these cases, we generally prefer immutability to aid in reasoning. If it's merely grouping return values, then you should use a tuple or namedtuple. If you need to return a mutated version of this result to higher in the call-stack, you can return a new tuple or namedtuple. In the case of a namedtuple, you can use `nt._replace` for convenience.

**Comment by briantaylor89** [comment]
Sorry I’m adamantly opposed to the use of globals.

The penalty associated with () is very minor in this context.  It’s syntactically ugly but it gives me the immutability I’m after.

As far as name tuple, I’d prefer not to add another class underneath.  Seems like overkill and adds difficulty to maintain.

Again mutability is for user convenience.   Creating a new named tuple will be messy and difficult if user just wants to change a single value.  Also it allows the value to be swept and therefore optimized.



Sent from my iPhone

On Dec 4, 2017, at 10:17 AM, James <notifications@github.com<mailto:notifications@github.com>> wrote:


A module-scoped function is no different than a module-scoped constant, given that the value itself can be assumed to be fixed. What we call "globals" in Python are module-scoped variables. They do not have the traditional downsides of "global" variables in languages that do not have modules.

In this case, there is no difference between a "global" function and a "global" constant, other than that the former requires () and has some execution and cognitive penalty. There is insufficient justification at this time to accept these penalties.

If the return value needs to be a mutable object with a single, coherent logical meaning, then you can create a class. Alternatively, if the call-stack is non-linear or the return value's lifetime is not scoped to its immediate call-stack, then a custom object is also a good idea. In these cases, we generally prefer immutability to aid in reasoning. If it's merely grouping return values, then you should use a tuple or namedtuple. If you need to return a mutated version of this result to higher in the call-stack, you can return a new tuple or namedtuple. In the case of a namedtuple, you can use nt._replace for convenience.

**Comment by dutc** [comment]
If you submit a pull request against the correct branch with the subset of these changes outside of this disagreement, I will merge those changes.

For the changes under disagreement, we will be following standard practice as I interpret it. In the case of mathematical or scientific constants, these should be module-level constants:
```
from math import pi, e
from scipy.constants import c
```

Please update your code to use `scipy.constants.c`: https://docs.scipy.org/doc/scipy/reference/constants.html

**Pull request closed without merging**
